// Generated by: GPT-4o (gpt-4o-2024-08-06)
// Prompt: MAC module, clk/rst/a(8-bit signed)/b(8-bit signed), out(32-bit signed),
//         synchronous active-high reset, always_ff, synthesizable SV only.

module mac (
    input  logic        clk,
    input  logic        rst,
    input  logic signed [7:0]  a,
    input  logic signed [7:0]  b,
    output logic signed [31:0] out
);

    always @(posedge clk) begin
        if (rst) begin
            out <= 32'b0;
        end else begin
            out <= out + {{16{a[7]}}, a} * {{16{b[7]}}, b};
        end
    end

endmodule
