// Generated by: Claude Sonnet 4.6
// Prompt: MAC module, clk/rst/a(8-bit signed)/b(8-bit signed), out(32-bit signed),
//         synchronous active-high reset, always_ff, synthesizable SV only.

module mac (
    input  logic        clk,
    input  logic        rst,
    input  logic [7:0]  a,
    input  logic [7:0]  b,
    output logic signed [31:0] out
);

    always_ff @(posedge clk) begin
        if (rst) begin
            out <= 32'sd0;
        end else begin
            out <= out + (a * b);
        end
    end

endmodule
